jQuery(function ($) {
    Highcharts.chart('if-container',
        {
            chart: {
                type: 'bar'
            },
            title: {
                text: 'Warlock Affliction T20M Patchwerk'
            },
            xAxis: {
                categories: [
                    "Kil'jaeden's Burning Wish",
                    "Unstable Arcano Crystal",
                    "Whispers in the Dark",
                    "Tarnished Sentinel Medallion",
                    "Erratic Metronome",
                    "Stat Stick (Mastery)",
                    "Dreadstone of Endless Shadows",
                    "Stat Stick (Haste)",
                    "Charm of the Rising Tide",
                    "Padawsen's Unlucky Charm",
                    "Stormsinger Fulmination Charge",
                    "Tome of Unraveling Sanity",
                    "Stat Stick (Crit)",
                    "Chrono Shard",
                    "Terror From Below",
                    "Stat Stick (Versatility)",
                    "Infernal Writ",
                    "PVP Badge of Dominance",
                    "Moonlit Prism",
                    "PVP Insignia of Dominance",
                    "Naraxas' Spiked Tongue",
                    "Obelisk of the Void",
                    "Star Gate",
                    "Darkmoon Deck: Hellfire",
                    "Horn of Valor",
                    "Spectral Thurible",
                    "Deteriorated Construct Core",
                    "Fury of the Burning Sky",
                    "Twisting Wind",
                    "Bough of Corruption",
                    "Devilsaur Shock-Baton",
                    "Portable Manacracker",
                    "Icon of Rot",
                    "Swarming Plaguehive",
                    "Oakheart's Gnarled Root",
                    "Infernal Alchemist Stone",
                    "Aran's Relaxing Ruby",
                    "Pharameres Forbidden Grimoire",
                    "Corrupted Starlight",
                    "Mrrgria's Favor",
                    "Caged Horror",
                    "Wriggling Sinew",
                    "Eye of Skovald",
                    "Elementium Bomb Squirrel Generator",
                    "Unstable Horrorslime",
                    "Figurehead of the Naglfar"
                ]
            },
            yAxis: {
                min: 0,
                title: {
                    text: '\u0394 Damage per second'
                },
                labels: {
                    enabled: true
                },
                stackLabels: {
                    enabled: false,
                    style: {
                        fontWeight: 'bold',
                        color: (Highcharts.theme && Highcharts.theme.textColor) || 'white'
                    }
                }
            },
            legend: {
                align: 'right',
                x: 0,
                verticalAlign: 'bottom',
                y: 0,
                floating: false,
                backgroundColor: (Highcharts.theme && Highcharts.theme.background2) || 'white',
                borderColor: '#CCC',
                borderWidth: 1,
                shadow: false,
                reversed: true
            },
            tooltip: {
                headerFormat: '<b>{point.x}</b>',
                formatter: function () {
                    var s = '<b>' + this.x + '</b>',
                        cumulative_amount = 0;
                    $.each(this.points.reverse(), function (i, point) {
                        cumulative_amount += point.y
                        if (point.y !== 0) {
                            s += '<br/>' + point.series.name + ':	' + cumulative_amount;
                        }
                    });
                    return s;
                },
                shared: true
            },
            plotOptions: {
                series: {
                    borderColor: '#151515'
                },
                bar: {
                    stacking: 'normal',
                    dataLabels: {
                        enabled: false,
                        color: (Highcharts.theme && Highcharts.theme.dataLabelsColor) || 'white'
                    }
                }
            },
            series: [
                {
                    name: "970",
                    color: "#FFEB3B",
                    data: [
                        132776,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0,
                        0
                    ]
                },
                {
                    name: '940',
                    color: '#00E676',
                    data: [
                        0,
                        3936,
                        6570,
                        6555,
                        6709,
                        5746,
                        5424,
                        6645,
                        8064,
                        7101,
                        6768,
                        7419,
                        5197,
                        4774,
                        5837,
                        5096,
                        5251,
                        5982,
                        6452,
                        5599,
                        4846,
                        4847,
                        7568,
                        0,
                        3734,
                        5253,
                        5661,
                        2533,
                        5757,
                        5662,
                        2888,
                        5673,
                        3107,
                        3440,
                        4095,
                        0,
                        3211,
                        3243,
                        2835,
                        2199,
                        1125,
                        2676,
                        1753,
                        2758,
                        2065,
                        1270
                    ]
                },
                {
                    name: '930',
                    color: '#db843d',
                    data: [
                        0,
                        4779,
                        7085,
                        7747,
                        6658,
                        5839,
                        7079,
                        7967,
                        4885,
                        5132,
                        6228,
                        7503,
                        6032,
                        6051,
                        5921,
                        6810,
                        7150,
                        5694,
                        3545,
                        5764,
                        2948,
                        4349,
                        4931,
                        0,
                        5854,
                        4882,
                        5472,
                        5256,
                        6167,
                        6277,
                        5209,
                        3831,
                        3862,
                        3442,
                        4300,
                        0,
                        2870,
                        3815,
                        1792,
                        3297,
                        4638,
                        3186,
                        3712,
                        1495,
                        1968,
                        173
                    ]
                },
                {
                    name: '920',
                    color: '#4198af',
                    data: [
                        0,
                        3885,
                        6768,
                        6200,
                        4658,
                        5988,
                        5289,
                        4307,
                        5744,
                        5423,
                        5017,
                        6050,
                        5874,
                        7091,
                        5383,
                        5518,
                        4254,
                        4335,
                        4206,
                        3707,
                        4574,
                        3472,
                        5972,
                        0,
                        3806,
                        2248,
                        5914,
                        3595,
                        5147,
                        4461,
                        3964,
                        6137,
                        4417,
                        2887,
                        3899,
                        0,
                        2687,
                        2931,
                        2976,
                        2990,
                        1344,
                        3182,
                        2721,
                        1330,
                        318,
                        1023
                    ]
                },
                {
                    name: '910',
                    color: '#71588f',
                    data: [
                        0,
                        4910,
                        5687,
                        4331,
                        5811,
                        5159,
                        5456,
                        5605,
                        4851,
                        5553,
                        5140,
                        4963,
                        4364,
                        4176,
                        5953,
                        4312,
                        5294,
                        5663,
                        5291,
                        4064,
                        4003,
                        4398,
                        4743,
                        0,
                        3829,
                        4750,
                        4579,
                        1791,
                        5253,
                        5202,
                        3824,
                        3726,
                        3328,
                        5121,
                        1800,
                        0,
                        3730,
                        3265,
                        2712,
                        3264,
                        2910,
                        1714,
                        1585,
                        3179,
                        427,
                        2100
                    ]
                },
                {
                    name: '900',
                    color: '#89a54e',
                    data: [
                        0,
                        3816,
                        4910,
                        4672,
                        3795,
                        4997,
                        3962,
                        3604,
                        5331,
                        4311,
                        4470,
                        65520,
                        5961,
                        4473,
                        3757,
                        4842,
                        4242,
                        4266,
                        2959,
                        4104,
                        3155,
                        4045,
                        4181,
                        4845,
                        3080,
                        2676,
                        3599,
                        4931,
                        3208,
                        4468,
                        2187,
                        5788,
                        1996,
                        1932,
                        4872,
                        4656,
                        1421,
                        2720,
                        1614,
                        2519,
                        2473,
                        2101,
                        2768,
                        2579,
                        3389,
                        686
                    ]
                },
                {
                    name: '890',
                    color: '#aa4643',
                    data: [
                        0,
                        3313,
                        4482,
                        71822,
                        4496,
                        4157,
                        4182,
                        4716,
                        66309,
                        4400,
                        4224,
                        0,
                        3317,
                        4646,
                        63513,
                        4775,
                        5025,
                        4899,
                        3043,
                        2903,
                        3219,
                        1620,
                        4353,
                        4152,
                        2854,
                        51010,
                        4650,
                        1276,
                        4239,
                        2623,
                        2922,
                        3124,
                        4217,
                        1722,
                        2344,
                        3336,
                        3923,
                        1876,
                        1520,
                        1593,
                        2097,
                        3624,
                        506,
                        1253,
                        0,
                        2173
                    ]
                },
                {
                    name: '880',
                    color: '#4572a7',
                    data: [
                        0,
                        98101,
                        78612,
                        0,
                        65819,
                        64336,
                        64556,
                        62751,
                        0,
                        62500,
                        60720,
                        0,
                        60641,
                        59925,
                        0,
                        57210,
                        56535,
                        52154,
                        54696,
                        50407,
                        51131,
                        51098,
                        41800,
                        63556,
                        49344,
                        0,
                        40221,
                        50292,
                        39862,
                        40723,
                        47254,
                        39727,
                        45223,
                        47452,
                        44619,
                        53699,
                        43016,
                        42903,
                        42152,
                        39531,
                        40545,
                        37630,
                        38177,
                        35134,
                        35968,
                        26436
                    ]
                }
            ]
        });
});